// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: stitcher.proto

package stitcherpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Stitcher_Process_FullMethodName = "/stitcher.Stitcher/Process"
)

// StitcherClient is the client API for Stitcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StitcherClient interface {
	Process(ctx context.Context, in *StitchRequest, opts ...grpc.CallOption) (*StitchResponse, error)
}

type stitcherClient struct {
	cc grpc.ClientConnInterface
}

func NewStitcherClient(cc grpc.ClientConnInterface) StitcherClient {
	return &stitcherClient{cc}
}

func (c *stitcherClient) Process(ctx context.Context, in *StitchRequest, opts ...grpc.CallOption) (*StitchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StitchResponse)
	err := c.cc.Invoke(ctx, Stitcher_Process_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StitcherServer is the server API for Stitcher service.
// All implementations must embed UnimplementedStitcherServer
// for forward compatibility.
type StitcherServer interface {
	Process(context.Context, *StitchRequest) (*StitchResponse, error)
	mustEmbedUnimplementedStitcherServer()
}

// UnimplementedStitcherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStitcherServer struct{}

func (UnimplementedStitcherServer) Process(context.Context, *StitchRequest) (*StitchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedStitcherServer) mustEmbedUnimplementedStitcherServer() {}
func (UnimplementedStitcherServer) testEmbeddedByValue()                  {}

// UnsafeStitcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StitcherServer will
// result in compilation errors.
type UnsafeStitcherServer interface {
	mustEmbedUnimplementedStitcherServer()
}

func RegisterStitcherServer(s grpc.ServiceRegistrar, srv StitcherServer) {
	// If the following call pancis, it indicates UnimplementedStitcherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Stitcher_ServiceDesc, srv)
}

func _Stitcher_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StitcherServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stitcher_Process_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StitcherServer).Process(ctx, req.(*StitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Stitcher_ServiceDesc is the grpc.ServiceDesc for Stitcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stitcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stitcher.Stitcher",
	HandlerType: (*StitcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _Stitcher_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stitcher.proto",
}
